export const fakeData = [
    {
        id: "1",
        name: "Halson Medical Co",
        website: "www.halsonmedical.com",
        linkedin: "www.linkedin.com/halsonmedical.com",
        overview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
        specialty: "Pain Management",
        services: "this is the services that the company offers (THIS WILL BE AN ARRAY)",
        therapeutic: "this is the therapeutic areas the company covers (THIS WILL BE AN ARRAY)",
        claimed: 1,
        image: "https://blog.capterra.com/wp-content/uploads/2019/10/HEAD-Top_9_Medical_Apps_for_Doctors_Hero_no_text.png"
    },
    {
        id: "2",
        name: "Blue Shield Co",
        website: "www.fakewebsite.com",
        linkedin: "www.fakelinkedin.com",
        overview: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
        specialty: "Heart Surgery",
        services: "this is the services that the company offers (THIS WILL BE AN ARRAY)",
        therapeutic: "this is the therapeutic areas the company covers (THIS WILL BE AN ARRAY)",
        claimed: 0,
        image: "https://miac.swiss/gallery/full/126/slider3@2x.jpg",
    },
    {
        id: "3",
        name: "Ironside Medicinals",
        website: "www.fakewebsite.com",
        linkedin: "www.fakelinkedin.com",
        overview: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
        specialty: "Knee Repair",
        services: "this is the services that the company offers (THIS WILL BE AN ARRAY)",
        therapeutic: "this is the therapeutic areas the company covers (THIS WILL BE AN ARRAY)",
        claimed: 0,
        image: "https://s3.amazonaws.com/tinycards/image/701e4715074bd2f39b81288e78109bde",
    },
]